#!/usr/bin/env python3
"""Generate the single-file notebook for molab.

molab is single-notebook-centric: it syncs one file from a GitHub URL, and
downloading a notebook brings just that file. So the shareable artifact cannot
import ``phd_boxprompt``. Rather than maintain a second copy by hand, this
inlines the package into the notebook's first cell.

``box_prompt.py`` stays the source of truth. Run this after changing either it
or the package:

    uv run python build_standalone.py

It fails loudly rather than emitting a subtly wrong file.
"""

from __future__ import annotations

import ast
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).parent
SOURCE_NOTEBOOK = ROOT / "notebooks" / "box_prompt.py"
OUTPUT_NOTEBOOK = ROOT / "notebooks" / "box_prompt_standalone.py"
PACKAGE = ROOT / "src" / "phd_boxprompt"
MODULES = [PACKAGE / "widget.py", PACKAGE / "qwen.py"]

BEGIN = "    # <<<INLINE-IMPORTS>>>"
END = "    # <<<END-INLINE-IMPORTS>>>"

BANNER = """# Generated by build_standalone.py — do not edit.
# Source of truth: box_prompt.py + phd_boxprompt/. Regenerate with:
#     uv run python build_standalone.py
"""


def module_body(path: Path) -> str:
    """A module's source, ready to live inside a function body.

    ``from __future__ import annotations`` is dropped because it is only legal
    at module level. That is safe on the versions we target: every annotation
    here (``X | Y``, ``list[str]``, ...) evaluates natively on 3.11+.
    """
    lines = [
        line
        for line in path.read_text().splitlines()
        if not line.startswith("from __future__ import")
    ]
    return textwrap.indent("\n".join(lines), "    ")


def build() -> str:
    notebook = SOURCE_NOTEBOOK.read_text()

    if BEGIN not in notebook or END not in notebook:
        raise SystemExit(
            f"markers {BEGIN.strip()} / {END.strip()} not found in {SOURCE_NOTEBOOK.name}; "
            "the inlining anchor was removed or renamed"
        )

    head, rest = notebook.split(BEGIN, 1)
    _, tail = rest.split(END, 1)

    inlined = "\n\n".join(
        f"    # ---- inlined from phd_boxprompt/{path.name} "
        f"{'-' * max(0, 58 - len(path.name))}\n\n{module_body(path)}"
        for path in MODULES
    )

    generated = BANNER + head + inlined + tail

    for expected in ("def box_widget(", "def detect_similar(", "def draw_detections("):
        if expected not in generated:
            raise SystemExit(f"generated notebook is missing {expected!r}")
    # Docstrings may mention the package; a real *import* of it would break
    # molab, so check the parsed tree rather than the raw text.
    tree = ast.parse(generated)
    leftover = [
        node
        for node in ast.walk(tree)
        if (isinstance(node, ast.ImportFrom) and (node.module or "").startswith("phd_boxprompt"))
        or (
            isinstance(node, ast.Import)
            and any(a.name.startswith("phd_boxprompt") for a in node.names)
        )
    ]
    if leftover:
        lines = ", ".join(f"line {node.lineno}" for node in leftover)
        raise SystemExit(f"generated notebook still imports the package at {lines}")

    return generated


def main() -> int:
    generated = build()
    previous = OUTPUT_NOTEBOOK.read_text() if OUTPUT_NOTEBOOK.exists() else None
    OUTPUT_NOTEBOOK.write_text(generated)

    status = "unchanged" if generated == previous else "written"
    print(f"{OUTPUT_NOTEBOOK.name}: {status} ({len(generated.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
