# Generated by build_standalone.py — do not edit.
# Source of truth: box_prompt.py + phd_boxprompt/. Regenerate with:
#     uv run python build_standalone.py
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "marimo",
#     "anywidget>=0.9.13",
#     "pillow>=10.4.0",
#     "traitlets>=5.14.3",
#     "openai>=1.60.0; sys_platform != 'emscripten'",
#     "python-dotenv>=1.0.1; sys_platform != 'emscripten'",
# ]
# ///

import marimo

__generated_with = "0.23.16"
app = marimo.App(width="medium")


@app.cell
def _():
    import io
    import json
    import os
    import time

    import marimo as mo
    from PIL import Image

    # ---- inlined from phd_boxprompt/widget.py -------------------------------------------------

    """An anywidget for drawing positive/negative example boxes on an image.

    Coordinates are always reported in *original image pixels*, independent of how
    the image is scaled in the browser. Use it from marimo like this::

        import marimo as mo
        from phd_boxprompt.widget import BoxDrawWidget, box_widget

        widget = mo.ui.anywidget(box_widget("folio.jpg"))
        widget  # display it

        widget.value["boxes"]  # -> [{"box": [x1, y1, x2, y2], "kind": "positive"}, ...]
    """


    import base64
    import io
    from pathlib import Path

    import anywidget
    import traitlets
    from PIL import Image

    __all__ = ["BoxDrawWidget", "box_widget"]

    # Longest edge of the preview sent to the browser. Coordinates stay in original
    # pixels; this only keeps the data URL from becoming enormous.
    PREVIEW_MAX_EDGE = 1600

    _ESM = r"""
    const SVG_NS = "http://www.w3.org/2000/svg";

    function render({ model, el }) {
      el.innerHTML = "";

      const root = document.createElement("div");
      root.className = "bp-root";

      // ---- toolbar -----------------------------------------------------------
      const bar = document.createElement("div");
      bar.className = "bp-bar";

      const makeButton = (text, extra) => {
        const button = document.createElement("button");
        button.type = "button";
        button.textContent = text;
        button.className = "bp-btn" + (extra ? " " + extra : "");
        return button;
      };

      const positiveButton = makeButton("＋ Positive", "bp-pos");
      const negativeButton = makeButton("－ Negative", "bp-neg");
      const undoButton = makeButton("Undo");
      const clearButton = makeButton("Clear");
      const counter = document.createElement("span");
      counter.className = "bp-count";

      bar.append(positiveButton, negativeButton, undoButton, clearButton, counter);

      // ---- stage -------------------------------------------------------------
      const stage = document.createElement("div");
      stage.className = "bp-stage";
      const img = document.createElement("img");
      img.draggable = false;
      img.alt = "Image to annotate";
      const svg = document.createElementNS(SVG_NS, "svg");
      svg.setAttribute("preserveAspectRatio", "none");
      const canvas = document.createElement("canvas");
      canvas.setAttribute("aria-label", "Drag to draw a bounding box");
      stage.append(img, svg, canvas);

      const empty = document.createElement("div");
      empty.className = "bp-empty";
      empty.textContent = "No image loaded. Upload one above, then drag over it to draw a box.";

      root.append(bar, stage, empty);
      el.append(root);

      // ---- state -------------------------------------------------------------
      let kind = model.get("kind") || "positive";
      let start = null;
      let current = null;
      let drawing = false;

      const width = () => Number(model.get("img_width")) || 0;
      const height = () => Number(model.get("img_height")) || 0;
      const boxes = () => model.get("boxes") || [];

      const commit = (next) => {
        model.set("boxes", next);
        model.save_changes();
      };

      const setKind = (next) => {
        kind = next;
        model.set("kind", next);
        model.save_changes();
        positiveButton.classList.toggle("bp-active", next === "positive");
        negativeButton.classList.toggle("bp-active", next === "negative");
      };

      // ---- painting ----------------------------------------------------------
      const syncImage = () => {
        const source = model.get("image");
        const hasImage = Boolean(source) && width() > 0 && height() > 0;
        stage.style.display = hasImage ? "block" : "none";
        empty.style.display = hasImage ? "none" : "grid";
        if (!hasImage) return;
        img.src = source;
        svg.setAttribute("viewBox", `0 0 ${width()} ${height()}`);
        canvas.width = width();
        canvas.height = height();
      };

      const drawBoxes = () => {
        while (svg.firstChild) svg.removeChild(svg.firstChild);
        const w = width();
        const h = height();
        if (!w || !h) return;
        const stroke = Math.max(2, Math.round(Math.min(w, h) / 200));
        const fontSize = Math.max(14, Math.round(Math.min(w, h) / 32));

        boxes().forEach((item, index) => {
          const [x1, y1, x2, y2] = item.box;
          const positive = item.kind === "positive";
          const color = positive ? "#16a34a" : "#dc2626";
          const label = `${positive ? "+" : "−"}${index + 1}`;

          const group = document.createElementNS(SVG_NS, "g");

          const rect = document.createElementNS(SVG_NS, "rect");
          rect.setAttribute("x", x1);
          rect.setAttribute("y", y1);
          rect.setAttribute("width", Math.max(0, x2 - x1));
          rect.setAttribute("height", Math.max(0, y2 - y1));
          rect.setAttribute("fill", "none");
          rect.setAttribute("stroke", color);
          rect.setAttribute("stroke-width", stroke);

          const tag = document.createElementNS(SVG_NS, "rect");
          tag.setAttribute("x", x1);
          tag.setAttribute("y", y1);
          tag.setAttribute("width", fontSize * 2.1);
          tag.setAttribute("height", fontSize + 6);
          tag.setAttribute("fill", color);

          const text = document.createElementNS(SVG_NS, "text");
          text.setAttribute("x", x1 + 5);
          text.setAttribute("y", y1 + fontSize);
          text.setAttribute("fill", "white");
          text.setAttribute("font-family", "sans-serif");
          text.setAttribute("font-size", fontSize);
          text.setAttribute("font-weight", "700");
          text.textContent = label;

          group.append(rect, tag, text);
          svg.append(group);
        });

        const positives = boxes().filter((b) => b.kind === "positive").length;
        const negatives = boxes().length - positives;
        counter.textContent = `${positives} positive · ${negatives} negative`;
      };

      const clearPreview = () => {
        const context = canvas.getContext("2d");
        context.clearRect(0, 0, canvas.width, canvas.height);
      };

      const drawPreview = () => {
        clearPreview();
        if (!start || !current) return;
        const context = canvas.getContext("2d");
        const stroke = Math.max(2, Math.round(Math.min(width(), height()) / 200));
        context.save();
        context.strokeStyle = kind === "positive" ? "#16a34a" : "#dc2626";
        context.lineWidth = stroke;
        context.setLineDash([stroke * 2, stroke * 1.5]);
        context.strokeRect(start.x, start.y, current.x - start.x, current.y - start.y);
        context.restore();
      };

      // ---- pointer handling --------------------------------------------------
      const pointAt = (event) => {
        const rect = canvas.getBoundingClientRect();
        const w = width();
        const h = height();
        return {
          x: Math.max(0, Math.min(w, Math.round(((event.clientX - rect.left) * w) / rect.width))),
          y: Math.max(0, Math.min(h, Math.round(((event.clientY - rect.top) * h) / rect.height))),
        };
      };

      canvas.addEventListener("pointerdown", (event) => {
        if (!width()) return;
        event.preventDefault();
        canvas.setPointerCapture(event.pointerId);
        drawing = true;
        start = pointAt(event);
        current = start;
        drawPreview();
      });

      canvas.addEventListener("pointermove", (event) => {
        if (!drawing) return;
        current = pointAt(event);
        drawPreview();
      });

      const finish = (event) => {
        if (!drawing) return;
        drawing = false;
        current = pointAt(event);
        const x1 = Math.min(start.x, current.x);
        const y1 = Math.min(start.y, current.y);
        const x2 = Math.max(start.x, current.x);
        const y2 = Math.max(start.y, current.y);
        start = null;
        current = null;
        clearPreview();
        if (x2 - x1 < 4 || y2 - y1 < 4) return;
        commit([...boxes(), { box: [x1, y1, x2, y2], kind }]);
      };

      canvas.addEventListener("pointerup", finish);
      canvas.addEventListener("pointercancel", () => {
        drawing = false;
        start = null;
        current = null;
        clearPreview();
      });

      positiveButton.addEventListener("click", () => setKind("positive"));
      negativeButton.addEventListener("click", () => setKind("negative"));
      undoButton.addEventListener("click", () => commit(boxes().slice(0, -1)));
      clearButton.addEventListener("click", () => commit([]));

      model.on("change:boxes", drawBoxes);
      model.on("change:image", () => {
        syncImage();
        drawBoxes();
      });
      model.on("change:img_width", syncImage);
      model.on("change:img_height", syncImage);

      setKind(kind);
      syncImage();
      drawBoxes();
    }

    export default { render };
    """

    _CSS = r"""
    .bp-root { width: 100%; font-family: var(--marimo-font, system-ui, sans-serif); }
    .bp-bar {
      display: flex; flex-wrap: wrap; gap: 0.4rem; align-items: center;
      margin-bottom: 0.5rem;
    }
    .bp-btn {
      padding: 0.28rem 0.7rem; border-radius: 6px; cursor: pointer;
      border: 1px solid #cbd5e1; background: #ffffff; color: #0f172a;
      font-size: 0.85rem; line-height: 1.3;
    }
    .bp-btn:hover { background: #f1f5f9; }
    .bp-pos.bp-active { background: #16a34a; border-color: #16a34a; color: #ffffff; }
    .bp-neg.bp-active { background: #dc2626; border-color: #dc2626; color: #ffffff; }
    .bp-count { margin-left: auto; font-size: 0.8rem; color: #64748b; }
    .bp-stage {
      position: relative; width: 100%; overflow: hidden;
      border: 1px solid #cbd5e1; border-radius: 8px; user-select: none;
      background: #f8fafc;
    }
    .bp-stage img { display: block; width: 100%; height: auto; pointer-events: none; }
    .bp-stage svg, .bp-stage canvas { position: absolute; inset: 0; width: 100%; height: 100%; }
    .bp-stage svg { z-index: 1; pointer-events: none; }
    .bp-stage canvas { z-index: 2; cursor: crosshair; touch-action: none; }
    .bp-empty {
      min-height: 220px; display: grid; place-items: center; padding: 2rem;
      border: 2px dashed #cbd5e1; border-radius: 8px; color: #64748b; text-align: center;
    }
    """


    class BoxDrawWidget(anywidget.AnyWidget):
        """Draw positive/negative example boxes over an image.

        Traits
        ------
        image : data URL of the (possibly downscaled) preview shown in the browser.
        img_width, img_height : size of the *original* image, in pixels.
        boxes : list of ``{"box": [x1, y1, x2, y2], "kind": "positive"|"negative"}``
            with coordinates in original-image pixels.
        kind : which kind the next drawn box will get.
        """

        _esm = _ESM
        _css = _CSS

        image = traitlets.Unicode("").tag(sync=True)
        img_width = traitlets.Int(0).tag(sync=True)
        img_height = traitlets.Int(0).tag(sync=True)
        boxes = traitlets.List(traitlets.Dict()).tag(sync=True)
        kind = traitlets.Unicode("positive").tag(sync=True)


    def _data_url(image: Image.Image) -> str:
        buffer = io.BytesIO()
        image.convert("RGB").save(buffer, format="JPEG", quality=92)
        encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
        return f"data:image/jpeg;base64,{encoded}"


    def box_widget(source: str | Path | bytes | Image.Image) -> BoxDrawWidget:
        """Build a :class:`BoxDrawWidget` from a path, raw bytes, or a PIL image."""
        if isinstance(source, Image.Image):
            image = source
        elif isinstance(source, bytes):
            image = Image.open(io.BytesIO(source))
        else:
            image = Image.open(Path(source))

        image = image.convert("RGB")
        original_width, original_height = image.size

        preview = image.copy()
        preview.thumbnail((PREVIEW_MAX_EDGE, PREVIEW_MAX_EDGE), Image.Resampling.LANCZOS)

        return BoxDrawWidget(
            image=_data_url(preview),
            img_width=original_width,
            img_height=original_height,
            boxes=[],
        )

    # ---- inlined from phd_boxprompt/qwen.py ---------------------------------------------------

    """Few-shot box prompting against Qwen3.8-Max, served through OpenRouter.

    The trick borrowed from the Gradio reference app: the example boxes are *drawn
    onto* the image before sending, and additionally passed as normalized
    coordinates in the text prompt. The model sees the exemplars both ways.

    Any vision model on OpenRouter works — set ``OPENROUTER_MODEL`` or pass
    ``model=``. Useful slugs:

    ``qwen/qwen3.8-max``          proprietary hosted version (default)
    ``qwen/qwen3.8-2.4t-a95b``    the open-weight MoE release

    Two transports, picked automatically:

    * CPython — the ``openai`` SDK, with token-by-token streaming.
    * Pyodide (a WASM-exported notebook in the browser) — ``pyodide.http.pyfetch``,
      since the SDK needs sockets the browser does not give us. Use the ``async``
      twin :func:`adetect_similar` there. No streaming on that path.
    """


    import base64
    import io
    import json
    import os
    import re
    import sys
    from collections.abc import Callable, Iterator, Mapping
    from dataclasses import dataclass
    from typing import Any

    from PIL import Image, ImageDraw

    __all__ = [
        "BoxPromptResult",
        "Detection",
        "adetect_similar",
        "adetect_similar",
        "annotate_prompt_boxes",
        "detect_similar",
        "draw_detections",
        "parse_detections",
        "resolve_api_key",
        "running_in_browser",
    ]

    DEFAULT_MODEL = "qwen/qwen3.8-max"
    DEFAULT_BASE_URL = "https://openrouter.ai/api/v1"

    POSITIVE_COLOR = "#16a34a"
    NEGATIVE_COLOR = "#dc2626"
    MATCH_COLOR = "#2563eb"

    MISSING_KEY_MESSAGE = (
        "No OpenRouter API key. Paste one into the key field in the notebook, or set "
        "OPENROUTER_API_KEY in the environment (or in a .env file). "
        "Keys are free to create at https://openrouter.ai/keys"
    )


    def running_in_browser() -> bool:
        """True when executing inside Pyodide, i.e. the WASM build."""
        return sys.platform == "emscripten"


    @dataclass(frozen=True)
    class Detection:
        """One returned box, in original-image pixels."""

        box: tuple[int, int, int, int]
        label: str


    @dataclass(frozen=True)
    class BoxPromptResult:
        """One box-prompt run: what came back, and how the model got there."""

        detections: list[Detection]
        answer: str
        reasoning: str = ""
        model: str = ""

        def __iter__(self):
            """Backwards-compatible ``detections, answer = detect_similar(...)``."""
            return iter((self.detections, self.answer))


    # --------------------------------------------------------------------------- #
    # image helpers
    # --------------------------------------------------------------------------- #


    def _data_url(image: Image.Image) -> str:
        buffer = io.BytesIO()
        image.convert("RGB").save(buffer, format="JPEG", quality=95)
        return "data:image/jpeg;base64," + base64.b64encode(buffer.getvalue()).decode("ascii")


    def annotate_prompt_boxes(image: Image.Image, boxes: list[dict[str, Any]]) -> Image.Image:
        """Return a copy of ``image`` with the exemplar boxes painted on it."""
        canvas = image.convert("RGB").copy()
        draw = ImageDraw.Draw(canvas)
        line_width = max(3, round(min(canvas.size) / 180))

        for index, annotation in enumerate(boxes, start=1):
            x1, y1, x2, y2 = (int(v) for v in annotation["box"])
            positive = annotation.get("kind") == "positive"
            color = POSITIVE_COLOR if positive else NEGATIVE_COLOR
            label = f" {'+' if positive else '-'}{index} "
            draw.rectangle((x1, y1, x2, y2), outline=color, width=line_width)
            text_box = draw.textbbox((x1, y1), label)
            draw.rectangle(text_box, fill=color)
            draw.text((x1, y1), label, fill="white")

        return canvas


    def draw_detections(
        image: Image.Image,
        prompt_boxes: list[dict[str, Any]],
        detections: list[Detection],
    ) -> Image.Image:
        """Paint exemplars (green/red) and model matches (blue) onto a copy."""
        canvas = annotate_prompt_boxes(image, prompt_boxes)
        draw = ImageDraw.Draw(canvas, "RGBA")
        line_width = max(2, round(min(canvas.size) / 260))

        for detection in detections:
            draw.rectangle(detection.box, outline=MATCH_COLOR, width=line_width)
            draw.rectangle(detection.box, fill=(37, 99, 235, 40))

        return canvas


    def normalized_box_summary(image: Image.Image, boxes: list[dict[str, Any]]) -> str:
        """Exemplar boxes as 0-1000 normalized XYXY, for the text half of the prompt."""
        width, height = image.size
        parts = []
        for annotation in boxes:
            x1, y1, x2, y2 = annotation["box"]
            normalized = [
                round(1000 * x1 / width),
                round(1000 * y1 / height),
                round(1000 * x2 / width),
                round(1000 * y2 / height),
            ]
            parts.append(f"{annotation.get('kind', 'positive')}: {normalized}")
        return "; ".join(parts)


    # --------------------------------------------------------------------------- #
    # response parsing
    # --------------------------------------------------------------------------- #


    def parse_detections(
        answer: str,
        width: int,
        height: int,
        preserve_labels: bool = False,
    ) -> list[Detection]:
        """Pull ``{"objects": [{"box_2d": [...]}]}`` out of the model's text.

        Raises ``ValueError`` if nothing parseable is found. It deliberately does not
        return an empty list on failure, so a parse error is never silently read as
        "the model found nothing".
        """
        fenced = re.search(r"```(?:json)?\s*([\s\S]*?)```", answer, flags=re.IGNORECASE)
        candidate = fenced.group(1) if fenced else answer

        object_match = re.search(r"\{[\s\S]*\}", candidate)
        list_match = re.search(r"\[[\s\S]*\]", candidate)
        if not (object_match or list_match):
            raise ValueError("no JSON object or array found in the model response")

        payload = json.loads((object_match or list_match).group(0))
        objects = payload.get("objects", []) if isinstance(payload, dict) else payload

        detections: list[Detection] = []
        for item in objects:
            coordinates = item.get("box_2d") or item.get("bbox") or item.get("box")
            if not isinstance(coordinates, list) or len(coordinates) != 4:
                continue
            x1, y1, x2, y2 = (float(v) for v in coordinates)
            x1, x2 = sorted((max(0.0, min(1000.0, x1)), max(0.0, min(1000.0, x2))))
            y1, y2 = sorted((max(0.0, min(1000.0, y1)), max(0.0, min(1000.0, y2))))
            pixel_box = (
                round(x1 * width / 1000),
                round(y1 * height / 1000),
                round(x2 * width / 1000),
                round(y2 * height / 1000),
            )
            label = str(item.get("label") or "match")[:80] if preserve_labels else "match"
            detections.append(Detection(box=pixel_box, label=label))

        return detections


    def _reasoning_from_blocks(details: Any) -> str:
        blocks: list[str] = []
        for block in details or []:
            if isinstance(block, dict):
                text = block.get("text") or block.get("summary") or block.get("data")
            else:
                text = getattr(block, "text", None) or getattr(block, "summary", None)
            if isinstance(text, str) and text.strip():
                blocks.append(text.strip())
        return "\n\n".join(blocks)


    def _extract_reasoning(message: Any) -> str:
        """Pull the reasoning trace out of a message, dict or SDK object alike.

        OpenRouter exposes it as ``reasoning`` (plain text) and/or
        ``reasoning_details`` (a list of blocks). Neither is guaranteed — some
        providers strip it, some models have none. Returns "" when absent.
        """
        if isinstance(message, Mapping):
            text = message.get("reasoning")
            if isinstance(text, str) and text.strip():
                return text.strip()
            return _reasoning_from_blocks(message.get("reasoning_details"))

        text = getattr(message, "reasoning", None)
        if isinstance(text, str) and text.strip():
            return text.strip()

        details = getattr(message, "reasoning_details", None)
        if not details:
            # Non-standard fields survive on model_extra rather than as attributes.
            extra = getattr(message, "model_extra", None) or {}
            if isinstance(extra.get("reasoning"), str):
                return str(extra["reasoning"]).strip()
            details = extra.get("reasoning_details")
        return _reasoning_from_blocks(details)


    def _delta_reasoning(delta: Any) -> str:
        """Reasoning text carried by one streamed delta, if any."""
        text = getattr(delta, "reasoning", None)
        if isinstance(text, str):
            return text
        extra = getattr(delta, "model_extra", None) or {}
        if isinstance(extra.get("reasoning"), str):
            return str(extra["reasoning"])
        blocks = extra.get("reasoning_details") or []
        return "".join(b.get("text", "") for b in blocks if isinstance(b, dict))


    # --------------------------------------------------------------------------- #
    # request construction
    # --------------------------------------------------------------------------- #


    def resolve_api_key(api_key: str | None = None) -> str:
        """Explicit key wins, then the environment. Raises with a helpful message."""
        key = (api_key or "").strip() or (os.getenv("OPENROUTER_API_KEY") or "").strip()
        if not key:
            raise RuntimeError(MISSING_KEY_MESSAGE)
        return key


    def _attribution_headers() -> dict[str, str]:
        """Optional OpenRouter attribution — cosmetic, only affects their rankings."""
        headers = {}
        if referer := os.getenv("OPENROUTER_SITE_URL"):
            headers["HTTP-Referer"] = referer
        if title := os.getenv("OPENROUTER_SITE_NAME"):
            headers["X-OpenRouter-Title"] = title
        return headers


    def _headers(api_key: str) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            **_attribution_headers(),
        }


    def _headers(api_key: str) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            **_attribution_headers(),
        }


    PROMPT_TEMPLATE = """
    The image contains visual box prompts drawn by the user. Green boxes marked with + are \
    positive examples of the object to find. Red boxes marked with - are negative examples \
    that must be ignored.

    The user's instruction is: {instruction}

    Find every other unboxed object in this same image that matches the positive examples \
    while respecting the negative examples. Return only valid JSON in this exact shape:

    {{"objects": [{{"label": "match", "box_2d": [x_min, y_min, x_max, y_max]}}]}}

    Use XYXY coordinates normalized to integers from 0 to 1000. Do not return the already \
    marked prompt boxes. If there are no additional matches, return {{"objects": []}}.

    For reference, the prompt boxes in normalized XYXY coordinates are: {box_summary}
    """.strip()


    def build_payload(
        image: Image.Image,
        boxes: list[dict[str, Any]],
        instruction: str = "",
        *,
        model: str | None = None,
        max_tokens: int = 8192,
        temperature: float = 0.0,
        reasoning: bool | str = True,
    ) -> dict[str, Any]:
        """The JSON body for one box-prompt request. Shared by both transports."""
        if not any(b.get("kind") == "positive" for b in boxes):
            raise ValueError("draw at least one positive box before running detection")

        instruction = instruction.strip() or (
            "Find every other unboxed object that visually matches the positive examples."
        )
        prompt = PROMPT_TEMPLATE.format(
            instruction=instruction,
            box_summary=normalized_box_summary(image, boxes),
        )
        annotated = annotate_prompt_boxes(image, boxes)

        payload: dict[str, Any] = {
            "model": model or os.getenv("OPENROUTER_MODEL", DEFAULT_MODEL),
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {"type": "image_url", "image_url": {"url": _data_url(annotated)}},
                    ],
                }
            ],
            "max_tokens": int(max_tokens),
            "temperature": temperature,
        }
        if reasoning:
            payload["reasoning"] = (
                {"effort": reasoning} if isinstance(reasoning, str) else {"enabled": True}
            )
        return payload


    def _finish(payload: dict[str, Any], answer: str, reasoning: str, size) -> BoxPromptResult:
        answer = answer.strip()
        if not answer:
            raise RuntimeError("the model returned no text; try raising max_tokens")
        width, height = size
        return BoxPromptResult(
            detections=parse_detections(answer, width, height),
            answer=answer,
            reasoning=reasoning.strip(),
            model=str(payload.get("model", "")),
        )


    # --------------------------------------------------------------------------- #
    # transport: CPython, via the openai SDK
    # --------------------------------------------------------------------------- #


    def _consume_stream(
        client: Any,
        request: dict[str, Any],
        on_chunk: Callable[[str, str], None],
    ) -> tuple[str, str]:
        """Stream a completion, reporting progress. Returns ``(answer, reasoning)``."""
        answer_parts: list[str] = []
        reasoning_parts: list[str] = []

        stream: Iterator[Any] = client.chat.completions.create(**request, stream=True)
        for chunk in stream:
            # OpenRouter interleaves keep-alive and usage frames with no choices.
            choices = getattr(chunk, "choices", None) or []
            if not choices:
                continue
            delta = getattr(choices[0], "delta", None)
            if delta is None:
                continue

            changed = False
            if content := getattr(delta, "content", None):
                answer_parts.append(str(content))
                changed = True
            if thought := _delta_reasoning(delta):
                reasoning_parts.append(thought)
                changed = True

            if changed:
                on_chunk("".join(reasoning_parts), "".join(answer_parts))

        return "".join(answer_parts), "".join(reasoning_parts)


    def detect_similar(
        image: Image.Image,
        boxes: list[dict[str, Any]],
        instruction: str = "",
        *,
        api_key: str | None = None,
        model: str | None = None,
        max_tokens: int = 8192,
        temperature: float = 0.0,
        reasoning: bool | str = True,
        on_chunk: Callable[[str, str], None] | None = None,
    ) -> BoxPromptResult:
        """Run one few-shot box prompt (CPython transport).

        ``boxes`` is the widget's value: ``[{"box": [x1, y1, x2, y2], "kind": ...}]``
        in original-image pixels. At least one positive box is required.

        ``api_key`` overrides ``OPENROUTER_API_KEY``; either may supply the key.

        ``reasoning`` asks OpenRouter for the model's reasoning trace. Pass ``True``
        to enable it, an effort level (``"low"``/``"medium"``/``"high"``) to tune it,
        or ``False`` to skip. Providers that do not support it are handled by
        retrying once without the parameter, so this never hard-fails a run.

        Pass ``on_chunk`` to stream. It is called with the accumulated
        ``(reasoning, answer)`` after every delta.
        """
        from openai import OpenAI

        payload = build_payload(
            image,
            boxes,
            instruction,
            model=model,
            max_tokens=max_tokens,
            temperature=temperature,
            reasoning=reasoning,
        )
        client = OpenAI(
            api_key=resolve_api_key(api_key),
            base_url=os.getenv("OPENROUTER_BASE_URL", DEFAULT_BASE_URL),
            timeout=180.0,
            max_retries=2,
        )

        request = {k: v for k, v in payload.items() if k != "reasoning"}
        request["extra_headers"] = _attribution_headers()
        if "reasoning" in payload:
            request["extra_body"] = {"reasoning": payload["reasoning"]}

        def call() -> tuple[str, str]:
            if on_chunk is None:
                completion = client.chat.completions.create(**request)
                message = completion.choices[0].message
                return str(message.content or ""), _extract_reasoning(message)
            return _consume_stream(client, request, on_chunk)

        try:
            answer, trace = call()
        except Exception:
            if "extra_body" not in request:
                raise
            # The provider rejected the reasoning parameter — rerun plainly.
            request.pop("extra_body", None)
            answer, trace = call()

        return _finish(payload, answer, trace, image.size)


    # --------------------------------------------------------------------------- #
    # transport: Pyodide, via the browser's fetch
    # --------------------------------------------------------------------------- #


    async def adetect_similar(
        image: Image.Image,
        boxes: list[dict[str, Any]],
        instruction: str = "",
        *,
        api_key: str | None = None,
        model: str | None = None,
        max_tokens: int = 8192,
        temperature: float = 0.0,
        reasoning: bool | str = True,
    ) -> BoxPromptResult:
        """Run one few-shot box prompt from a browser (Pyodide) notebook.

        Uses ``pyodide.http.pyfetch`` because the ``openai`` SDK needs sockets that
        WASM does not provide. OpenRouter serves permissive CORS headers, so the
        request works directly from the page. No streaming on this path.
        """
        from pyodide.http import pyfetch  # noqa: PLC0415 — only exists in Pyodide

        payload = build_payload(
            image,
            boxes,
            instruction,
            model=model,
            max_tokens=max_tokens,
            temperature=temperature,
            reasoning=reasoning,
        )
        base = os.getenv("OPENROUTER_BASE_URL", DEFAULT_BASE_URL).rstrip("/")

        response = await pyfetch(
            f"{base}/chat/completions",
            method="POST",
            headers=_headers(resolve_api_key(api_key)),
            body=json.dumps(payload),
        )
        if response.status != 200:
            detail = (await response.string())[:400]
            raise RuntimeError(f"OpenRouter returned HTTP {response.status}: {detail}")

        data = await response.json()
        if error := data.get("error"):
            raise RuntimeError(f"OpenRouter error: {error}")

        message = data["choices"][0]["message"]
        return _finish(
            payload,
            str(message.get("content") or ""),
            _extract_reasoning(message),
            image.size,
        )

    # A .env file is a convenience, not a requirement — and python-dotenv is not
    # installed in the browser build.
    try:
        from dotenv import load_dotenv

        load_dotenv()
    except Exception:
        pass
    return (
        Image,
        adetect_similar,
        box_widget,
        detect_similar,
        draw_detections,
        io,
        json,
        mo,
        os,
        running_in_browser,
        time,
    )


@app.cell
def _(mo):
    mo.md(
        """
        # Box prompting

        Drop an image below, draw one or two **example boxes** on it, and ask the
        model to find the rest. Coordinates are reported in original-image pixels.
        """
    )
    return


@app.cell
def _(mo, os):
    api_key_input = mo.ui.text(
        label="OpenRouter API key",
        placeholder="sk-or-…",
        kind="password",
        full_width=True,
    )
    key_from_env = bool((os.getenv("OPENROUTER_API_KEY") or "").strip())
    return api_key_input, key_from_env


@app.cell
def _(api_key_input, key_from_env, mo):
    if api_key_input.value.strip():
        key_status = "Using the key you pasted below."
    elif key_from_env:
        key_status = "Using `OPENROUTER_API_KEY` from the environment — no need to paste one."
    else:
        key_status = (
            "No key found. Paste one below — get a free key at "
            "[openrouter.ai/keys](https://openrouter.ai/keys). "
            "It stays in this browser tab and is never written to disk."
        )

    mo.vstack([mo.callout(mo.md(key_status), kind="info"), api_key_input])
    return (key_status,)


@app.cell
def _(mo):
    upload = mo.ui.file(
        kind="area",
        filetypes=[".png", ".jpg", ".jpeg", ".webp", ".tif", ".tiff"],
        multiple=False,
        label="Drop a folio here, or click to browse",
        max_size=50_000_000,
    )
    upload
    return (upload,)


@app.cell
def _(Image, io, mo, upload):
    mo.stop(not upload.value, mo.md("*Waiting for an image.*"))

    image = Image.open(io.BytesIO(upload.contents(0))).convert("RGB")
    mo.md(f"**{upload.name(0)}** — {image.width} × {image.height} px")
    return (image,)


@app.cell
def _(box_widget, image, mo):
    widget = mo.ui.anywidget(box_widget(image))
    widget
    return (widget,)


@app.cell
def _(mo, widget):
    boxes = widget.value["boxes"]
    positives = [b for b in boxes if b["kind"] == "positive"]

    instruction = mo.ui.text_area(
        label="What should the model find?",
        placeholder="e.g. Find every other speech scroll. Ignore the rubricated caption strip.",
        rows=3,
        full_width=True,
    )
    run = mo.ui.run_button(label="Run detection", disabled=not positives)

    mo.vstack(
        [
            mo.md(
                f"`{len(positives)}` positive · `{len(boxes) - len(positives)}` negative"
                + ("" if positives else " — draw at least one green box to enable the run.")
            ),
            instruction,
            run,
        ]
    )
    return boxes, instruction, run


@app.cell
async def _(
    adetect_similar,
    api_key_input,
    boxes,
    detect_similar,
    image,
    instruction,
    mo,
    run,
    running_in_browser,
    time,
):
    mo.stop(not run.value, mo.md("*Draw your boxes, then click **Run detection**.*"))

    # Every replace() re-serialises and broadcasts the whole block, so cap the
    # refresh rate rather than repainting on each token.
    last_paint = [0.0]
    REFRESH_SECONDS = 0.1

    def show_progress(reasoning_so_far: str, answer_so_far: str) -> None:
        now = time.monotonic()
        if now - last_paint[0] < REFRESH_SECONDS:
            return
        last_paint[0] = now
        panels = []
        if reasoning_so_far:
            panels.append(mo.md(f"**Reasoning…**\n\n{reasoning_so_far}"))
        panels.append(mo.md(f"**Response…**\n\n```json\n{answer_so_far or '▌'}\n```"))
        mo.output.replace(mo.vstack(panels))

    key = api_key_input.value.strip() or None

    if running_in_browser():
        # Pyodide has no sockets, so no streaming here — one awaited fetch.
        mo.output.replace(mo.md("**Asking the model…** (no live stream in the browser)"))
        result = await adetect_similar(image, boxes, instruction.value, api_key=key)
    else:
        result = detect_similar(
            image, boxes, instruction.value, api_key=key, on_chunk=show_progress
        )

    mo.output.replace(
        mo.md(f"Done — **{len(result.detections)}** match(es) from `{result.model}`.")
    )
    return (result,)


@app.cell
def _(boxes, draw_detections, image, mo, result):
    mo.vstack(
        [
            mo.md(f"### {len(result.detections)} match(es)"),
            mo.image(draw_detections(image, boxes, result.detections), width=900),
        ]
    )
    return


@app.cell
def _(mo, result):
    mo.md(
        f"## Reasoning\n\n{result.reasoning}"
        if result.reasoning
        else "## Reasoning\n\n*This provider returned no reasoning trace for the run.*"
    )
    return


@app.cell
def _(boxes, instruction, json, mo, result):
    record = {
        "model": result.model,
        "instruction": instruction.value,
        "prompt_boxes": boxes,
        "detections": [{"box": list(d.box), "label": d.label} for d in result.detections],
        "reasoning": result.reasoning,
    }

    mo.accordion(
        {
            "Result as JSON (copy this into your notes)": mo.md(
                f"```json\n{json.dumps(record, indent=2)}\n```"
            ),
            "Raw model response": mo.md(f"```json\n{result.answer}\n```"),
        }
    )
    return


if __name__ == "__main__":
    app.run()
